/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;


import classes.Customer;
import dbconnect.Order;
import dbconnect.OrganicFood;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dileeka
 */
public class CustomerMenue extends javax.swing.JFrame {

     Connection con;
    Statement stmt;
    ResultSet rs=null;
    PreparedStatement pst;
    public CustomerMenue() {
        con= Order.ConnectItem();
        initComponents();
    }
    
    
    public void Update(){
          try{
        String sql="select * from DILEEKA.FRUITS";
        pst=con.prepareStatement(sql);
        rs =pst.executeQuery();
        tablefood.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception ex){
            
        }
          
    }
    public void Updatemeat(){
          try{
        String sql="select * from DILEEKA.MEATS";
        pst=con.prepareStatement(sql);
        rs =pst.executeQuery();
        tablefood.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception ex){
            
        }
          
    }
    public void Updatespicies(){
          try{
        String sql="select * from DILEEKA.SPICIES";
        pst=con.prepareStatement(sql);
        rs =pst.executeQuery();
        tablefood.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception ex){
            
        }
          
    }
    public void Updatevegetables(){
          try{
        String sql="select * from DILEEKA.VEGETABLES";
        pst=con.prepareStatement(sql);
        rs =pst.executeQuery();
        tablefood.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception ex){
            
        }
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg = new javax.swing.JOptionPane();
        jOptionPane1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablefood = new javax.swing.JTable();
        cmbfood = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtlocation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmanu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablefood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablefood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablefoodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablefood);

        cmbfood.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cmbfood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fruits", "Vegetables" }));
        cmbfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbfoodActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("ItemName");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Price");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Location");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Quantity");

        txtquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantityActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Manufacture Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Select Item Details");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setText("Customer Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmanu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(cmbfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtmanu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s=cmbfood.getSelectedItem().toString();
        if("Fruits".equals(s)){
        try{
        String sql="select * from FRUITS ";
        pst=con.prepareStatement(sql);
        rs =pst.executeQuery();
        tablefood.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception ex){
            
        }
        }
     
        
      
            if("Vegetables".equals(s)){
        try{
        String sql="select * from VEGETABLES ";
        pst=con.prepareStatement(sql);
        rs =pst.executeQuery();
        tablefood.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception ex){
            
        }
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantityActionPerformed

    private void tablefoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablefoodMouseClicked
        String select=cmbfood.getSelectedItem().toString();
        if(select.equals("Fruits")){
            try {
                int raw=tablefood.getSelectedRow();
                String enter=tablefood.getModel().getValueAt(raw,0).toString();
                String SQL="select * from Fruits where FRUITSNAME='"+enter+"'";
                pst=con.prepareStatement(SQL);
                rs=pst.executeQuery();
                if(rs.next()){
                String val1=rs.getString("FRUITSNAME");
                txtname.setText(val1);
                 String val2=rs.getString("PRICE");
                txtprice.setText(val2);
                String val3=rs.getString("LOCATION");
                txtlocation.setText(val3);
                String val4=rs.getString("QUANTITY");
                txtquantity.setText(val4);
                String val5=rs.getString("MANUFACTUREDATE");
                txtmanu.setText(val5);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
  
        }
        else if(select.equals("Meats")){
            try {
                int raw=tablefood.getSelectedRow();
                String enter=tablefood.getModel().getValueAt(raw,0).toString();
                String SQL="select * from Meats where MEATNAME='"+enter+"'";
                pst=con.prepareStatement(SQL);
                rs=pst.executeQuery();
                if(rs.next()){
                String val1=rs.getString("MEATNAME");
                txtname.setText(val1);
                 String val2=rs.getString("PRICE");
                txtprice.setText(val2);
                String val3=rs.getString("LOCATION");
                txtlocation.setText(val3);
                String val4=rs.getString("QUANTITY");
                txtquantity.setText(val4);
                String val5=rs.getString("MANUFACTUREDATE");
                txtmanu.setText(val5);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
  
        }
         else if(select.equals("Spicies")){
            try {
                int raw=tablefood.getSelectedRow();
                String enter=tablefood.getModel().getValueAt(raw,0).toString();
                String SQL="select * from Spicies where SPICIESNAME='"+enter+"'";
                pst=con.prepareStatement(SQL);
                rs=pst.executeQuery();
                if(rs.next()){
                String val1=rs.getString("SPICIESNAME");
                txtname.setText(val1);
                 String val2=rs.getString("PRICE");
                txtprice.setText(val2);
                String val3=rs.getString("LOCATION");
                txtlocation.setText(val3);
                String val4=rs.getString("QUANTITY");
                txtquantity.setText(val4);
                String val5=rs.getString("MANUFACTUREDATE");
                txtmanu.setText(val5);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
  
        }
         else if (select.equals("Vegetables")){
            try {
                int raw=tablefood.getSelectedRow();
                String enter=tablefood.getModel().getValueAt(raw,0).toString();
                String SQL="select * from Vegetables where VEGETABLESNAME='"+enter+"'";
                pst=con.prepareStatement(SQL);
                rs=pst.executeQuery();
                if(rs.next()){
                String val1=rs.getString("VEGETABLESNAME");
                txtname.setText(val1);
                 String val2=rs.getString("PRICE");
                txtprice.setText(val2);
                String val3=rs.getString("LOCATION");
                txtlocation.setText(val3);
                String val4=rs.getString("QUANTITY");
                txtquantity.setText(val4);
                String val5=rs.getString("MANUFACTUREDATE");
                txtmanu.setText(val5);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
  
        }
    }//GEN-LAST:event_tablefoodMouseClicked

    private void cmbfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbfoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbfoodActionPerformed
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbfood;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JOptionPane msg;
    private javax.swing.JTable tablefood;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtmanu;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
